### ISSUE TITLE
Chỉnh sửa lại phần loading data cho hợp lý 

### ISSUE THREAD

**Issue by harrytran998** [Olympus-Team/OKRs-enterprise-frontend#310]
Đang loading hết, kể cả title cố định, VD --> OKRs page
```
Chỉ nên loading những cái mà có thay đổi data
```
VD: Giữ nguyên title OKRs công ty, OKRs nhóm và OKRs cá nhân
![image](https://user-images.githubusercontent.com/24296018/91659955-3846a200-eafd-11ea-9255-0e01a1f3421f.png)

Giữ nguyên title Phản hồi cho Team Leader, Phản hồi cho ...
![image](https://user-images.githubusercontent.com/24296018/91660013-a55a3780-eafd-11ea-86aa-717018510ed5.png)

Giữ nguyên title OKRs và Top sao nhận được, cho đi
![image](https://user-images.githubusercontent.com/24296018/91660595-249d3a80-eb01-11ea-977d-c2e3a5508998.png)

**Comment by bacodekiller** [comment]
Cái này muốn làm thế phải bọc thêm div => k ổn. Để như cũ là oke r
