### ISSUE TITLE
Chưa trả ra message giống response của API

### ISSUE THREAD

**Issue by phanduc0908** [Olympus-Team/OKRs-enterprise-frontend#86]
**Describe the bug**
 +  Phần Update Vị trí công việc
 + Khi edit 1 job position đã tồn tại

**Expected behavior**
  => Mong muốn hiện thi message: "Vị trí công việc đã tồn tại"

**Screenshots**
![image](https://user-images.githubusercontent.com/29729545/88940738-50cf5c80-d2b2-11ea-9885-a6ad6255ae16.png)

**Comment by harrytran998** [comment]
@quangnv281098 Update status code chưa đó
